### PR TITLE
Support SD-JWT support and issuer metadata

### PR DESCRIPTION
**Pull request by phisakel**
Introduce support for sdJwtVc credential metadata, improve metadata management, and refactor various components for better handling of document types and claims. Update dependencies and documentation accordingly.

### CODE REVIEW

**Comment by phisakel** [comment]
Closes #138

**Comment by phisakel** [comment]
Closes #135

**Comment by phisakel** [comment]
Closes #128

**Comment by phisakel** [comment]
Closes #129

**Review by marinaioannou — APPROVED** [review]

**Pull request merged**
